Recommender system/Controllers/DataEntryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using Recommender_system.Models;

namespace Recommender_system.Controllers
{
    public class DataEntryController : BaseController
    {
        SRDB db = new SRDB();
        // GET: DataEntry
        public ActionResult Index()
        {
            return View();
        }

        // GET: DataEntry/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DataEntry/Create
        public async Task<ActionResult> Create()
        {
            var user = await GetUser();
            return View();
        }

        // POST: DataEntry/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(DataEntryUser data_entry)
        {
            Session["perdoruesi"] = null;
            var user = await GetUser();
            MessageJS returnmodel = new MessageJS();
            if (ModelState.IsValid)
            {
                try
                {
                    USER_DATA addmodel = new USER_DATA();
                    addmodel.ID = data_entry.ID;
                    addmodel.BloodGlucose = data_entry.Glukoza;
                    addmodel.UserID = user.ID;
                    var bmi = Convert.ToDouble(data_entry.Pesha) / Math.Pow(Convert.ToDouble(data_entry.Gjatesia/100),2);
                    addmodel.BMI = Convert.ToDecimal(bmi.ToString("0.00"));

                    var lista = db.USER_DATA.Where(q=>q.UserID!=user.ID).ToList();
               
                    List<ListaKnn> lista_knn = new List<ListaKnn>();
                    double neighbors_distance = 0;
                    foreach (var item in lista)
                    {
                        var distanca = Math.Pow(Convert.ToDouble(item.BMI.Value - Convert.ToDecimal(bmi)), 2) + Math.Pow(Convert.ToDouble(item.BloodGlucose.Value - data_entry.Glukoza), 2);
                        neighbors_distance = Math.Sqrt(distanca);
                        lista_knn.Add(new ListaKnn()
                        {
                            distanca = neighbors_distance,
                            userID = item.UserID.Value,
                            classification=item.HasDiabet.Value
                            
                        });
                    }
                    //knn
                    int k = 5;
                    var selekto_perdoruesit = (from t in lista_knn orderby t.distanca descending select t).ToList().Take(k);
                    var count_false = (from bashkesia in selekto_perdoruesit where bashkesia.classification = false select bashkesia).ToList();
                    var count_true = (from bashkesia in selekto_perdoruesit where bashkesia.classification = true select bashkesia).ToList();

                    bool klasifikimi = false;
                    var perdoruesit_me_afert = count_false.OrderByDescending(q => q.distanca).FirstOrDefault();

                    if (count_false.Count() < count_true.Count())
                    {
                        klasifikimi = true;
                        perdoruesit_me_afert = count_true.OrderByDescending(q => q.distanca).FirstOrDefault();
                    } 
                    Session["perdoruesi"] = db.USER_DATA.Where(q => q.UserID == perdoruesit_me_afert.userID).FirstOrDefault();
                    addmodel.HasDiabet = klasifikimi;
                    db.USER_DATA.Add(addmodel);
                    await db.SaveChangesAsync();
                    returnmodel.Status = true;
                    returnmodel.ID = addmodel.ID;
                    return Json(returnmodel, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    returnmodel.Status = false;
                    returnmodel.Message = "Ka ndodhur një gabim";
                    return Json(returnmodel, JsonRequestBehavior.DenyGet);
                }
            }
            else
            {
                var errors = ModelState.Select(x => x.Value.Errors)
                       .Where(y => y.Count > 0)
                       .ToList();
            }
            returnmodel.Status = false;
            return Json(returnmodel, JsonRequestBehavior.DenyGet);

        }

        // GET: DataEntry/Edit/5
        public async Task<ActionResult> Rekomandimet()
        {
            var user = await GetUser();
            var rekomandimet =(USER_DATA)Session["perdoruesi"];
            var meals = db.USER_RATING.ToList();

            if(rekomandimet !=null)
            {
                 meals = db.USER_RATING.Where(q => q.UserID == rekomandimet.UserID).OrderByDescending(q => q.RatingID).Take(4).ToList();
                if(meals.Count()==0)
                {
                    var rand = new Random();
                    var lista = db.USER_RATING.Take(30).ToList();
                    List<USER_RATING> ushqimet = new List<USER_RATING>();
                    for (int i = 0; i < 6; i++)
                    {
                        int r = rand.Next(lista.Count);
                        USER_RATING m = lista.Skip(r).First();
                        if (!ushqimet.Contains(m))
                        {
                            ushqimet.Add(m);
                        }
                    }
                    meals = ushqimet;
                }
             
            }
            else
            {
                 meals = db.USER_RATING.Take(4).ToList();
            }


            return View(meals);
        }

        // POST: DataEntry/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: DataEntry/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DataEntry/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Recommender system/Controllers/RekomandimetController.cs
using Recommender_system.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Recommender_system.Controllers
{
    public class RekomandimetController : BaseController
    {
        SRDB db = new SRDB();
        public ActionResult Index()
        {
           var rand = new Random();
            var lista = db.MEALS.ToList();
            List<MEAL> ushqimet = new List<MEAL>();
            for (int i = 0; i < 6; i++)
            {
                int r = rand.Next(lista.Count);
                MEAL m = lista.Skip(r).First();
                if (!ushqimet.Contains(m))
                {
                    ushqimet.Add(m);
                }  
            }
            return View(ushqimet);
        }
        public async Task<ActionResult> CalculatePearson(IList<USER_RATING> meals_model)
        {
            Session["meals"] = null;
            Session["listaPerfundimtare"] = null;
            var user = await GetUser();

            MessageJS returnmodel = new MessageJS();
            List<Pearson_Corelation> pearson_corelation = new List<Pearson_Corelation>();

            if (ModelState.IsValid)
            {
                try
                { 
                    //kshyrmi ne db qe contains krejt qeto meals qe i ban rating useri

                    var meals_db = db.USER_RATING.Where(q => q.UserID != user.ID).Select(q => q.MealID).ToList();

                    var meals_common = meals_model.Where(c => meals_db.Contains(c.MealID)).Select(q=>q.MealID).ToList();

                    //mirret lista e itemsave nga db per qeto meals (vetem userat e ngjajshem)
                    var lista = db.USER_RATING.Where(q => meals_common.Contains(q.MealID)).ToList();

                    float Pearson_Score = 0;
 
                    //grupimi ne baze te userave
                    foreach (var item in lista.GroupBy(q=>q.UserID))
                    {
                        List<int> item_in_corelation = new List<int>();

                        List<int> item_in_corelation_db = new List<int>();

                        //secili rating per meals te njejte te user i qasur dhe userave te tjere futet ne listat perkatese
                        foreach (var item1 in item)
                        {
                            var lista_userit = meals_model.Where(q => q.MealID == item1.MealID).FirstOrDefault();
                            if(lista_userit != null)
                            {
                                item_in_corelation.Add(lista_userit.RatingID);

                                item_in_corelation_db.Add(item1.RatingID);
                            }
                            else
                            {
                                break;
                            }
                        }
                        //kalkulohet pearson
                       
                        Pearson_Score= Coleration(item_in_corelation, item_in_corelation_db, item_in_corelation.Count());

                        pearson_corelation.Add(new Pearson_Corelation { UserID = item.Key, PearsonScore= Pearson_Score});
                    }

                    //most similar scores;
                    var lista_perfundimtare = pearson_corelation.OrderByDescending(q => q.PearsonScore).Take(3).ToList();

                    Session["listaPerfundimtare"] = lista_perfundimtare;

                    Session["meals"] = meals_model.ToList();

                    //insertimi i te dhenave ne baze

                    
                    foreach(var item in meals_model)
                    {
                        USER_RATING model = new USER_RATING();

                        var exist = db.USER_RATING.Any(q => q.MealID == item.MealID && q.UserID == user.ID);

                        var ratings = db.USER_RATING.Where(q => q.MealID == item.MealID && q.UserID == user.ID).ToList();

                        model.UserID = user.ID;

                        var average_rating = (item.RatingID + ratings.Sum(q => q.RatingID))/(1+ratings.Count());

                        model.RatingID = item.RatingID;

                        model.MealID = item.MealID;

                        
                        if(!exist)
                        {
                            db.USER_RATING.Add(model);
                        }
                     
                        
                        await db.SaveChangesAsync();
                    }
                  

                    returnmodel.Message = "Sukses";
                    returnmodel.Status = true;
                    return Json(returnmodel, JsonRequestBehavior.AllowGet);

                }
                catch (Exception ex)
                {
                    returnmodel.Message = "Ka ndodhur nje gabim";
                    returnmodel.Status = false;
                    return Json(returnmodel, JsonRequestBehavior.AllowGet);
                }
            }

            return Json(returnmodel, JsonRequestBehavior.AllowGet);
        }



       public static float Coleration(List<int> X, List<int> Y, int n)
        {
            int sum_X = 0, sum_Y = 0, sum_XY = 0;
            int squareSum_X = 0, squareSum_Y = 0;

            for (int i = 0; i < n; i++)
            {
                // shuma e elementeve te listes X 
                sum_X = sum_X + X[i];

                // shuma e elementeve te listes Y 
                sum_Y = sum_Y + Y[i];

                //shuma  X[i] * Y[i]
                sum_XY = sum_XY + X[i] * Y[i];

                // shuma e katroreve te elementeve te listave 
                squareSum_X = squareSum_X + X[i] * X[i];
                squareSum_Y = squareSum_Y + Y[i] * Y[i];
            }

            // formula per kalkulimin e Korelacionit te Pearsonit
            float correlation = (float)(n * sum_XY - sum_X * sum_Y) /
                         (float)(Math.Sqrt((n * squareSum_X -
                         sum_X * sum_X) * (n * squareSum_Y -
                         sum_Y * sum_Y)));

            return correlation;
        }

        public async Task<ActionResult> WeightedAverageSum()
        {
            var user = await GetUser();
            var scores_users = (List<Pearson_Corelation>)Session["listaPerfundimtare"];
            var meals= (List<USER_RATING>)Session["meals"];

            List<MEAL> rekomandimet = new List<MEAL>();
            var lista1 = scores_users.Select(q => q.UserID).ToList();
            var lista2 = meals.Select(q => q.MealID).ToList();

            var others= db.USER_RATING.Where(p => lista1.Contains(p.UserID) && 
            !lista2.Contains(p.MealID)).ToList();

            if(others.Count()>0)
            {
                List<Weighted_Sum> weighted_Sums = new List<Weighted_Sum>();
                var particioni = others.GroupBy(q => q.MealID);

                float average_weighted_sum = 0;
                float sum_of_similarities = 0;

                foreach (var item in particioni)
                {
                    //duhet veq per ratings e perbashket
                    if (item.Count() == others.GroupBy(q => q.UserID).Count())
                    {

                        foreach (var item1 in item)
                        {
                            float similarity = scores_users.Where(q => q.UserID == item1.UserID).Select(q => q.PearsonScore).FirstOrDefault();
                            average_weighted_sum += item1.RatingID * similarity;
                            sum_of_similarities += similarity;
                        }

                        weighted_Sums.Add(new Weighted_Sum { MealID = item.Key, Average_Score = Math.Round(average_weighted_sum / sum_of_similarities, 0, MidpointRounding.AwayFromZero)});
                    } 
                }
                //marrim itemsat me rating me te larte
               var get_the_best= weighted_Sums.OrderByDescending(q => q.Average_Score).Select(q=>q.MealID).Take(5);
               var lista_fundit = db.MEALS.Where(q=> get_the_best.Contains(q.ID)).ToList();
               rekomandimet = lista_fundit;
            }
            else
            {
                Random rand = new Random();
                var lista = db.MEALS.Take(20).ToList();
                for (int i = 0; i < 5; i++)
                {
                    int r = rand.Next(lista.Count);
                    MEAL m = lista.Skip(r).First();
                    if (!rekomandimet.Contains(m))
                    {
                        rekomandimet.Add(m);
                    }         
                }
            }

            return View(rekomandimet);
        }
    }

}

Recommender system/Views/DataEntry/Create.cshtml
@model Recommender_system.Models.USER_DATA

@Html.AntiForgeryToken()

<div class="panel panel-white">
    <div class="panel-body">
        <div class="row">
            <div class="col-md-4">
                <div class="form-horizontal">
                    <fieldset>
                        <legend>
                            Jep të dhenat e  tua
                        </legend>
                        <div class="form-group">
                            <label>
                                Niveli i glukozës <span class="symbol required"></span>
                            </label>
                            <input type="text" class="form-control" id="Glukoza" placeholder="Niveli i glukozës" onkeypress="return isNumberKey(event)">
                        </div>
                        <div class="form-group">
                            <label>
                                Gjatësia juaj (në cm) <span class="symbol required"></span>
                            </label>
                            <input type="text" placeholder="Gjatësia" id="Gjatesia" class="form-control" onkeypress="return isNumberKey(event)">
                        </div>
                        <div class="form-group">
                            <label>
                                Pesha në kg <span class="symbol required"></span>
                            </label>
                            <input type="number" placeholder="Pesha" id="Pesha" class="form-control" onkeypress="return isNumberKey(event)">
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button type="button" onclick="regjistro(this)" class="btn btn-primary" data-toggle="modal" data-target="#registerModal">Rekomando</button>
                            </div>
                        </div>
                    </fieldset>

                </div>
            </div>
            <div class="col-md-8">
                <div id="timeline">
                    <div class="timeline">
                        <div class="spine"></div>
                        <div class="date_separator" id="november">
                            <span>FAKTE</span>
                        </div>
                        <ul class="columns">
                            <li>
                                <div class="timeline_element partition-white">
                                    <div class="timeline_title">
                                        <i class="fa fa-hospital-o fa-2x pull-left fa-border"></i>
                                        <h4 class="light-text no-margin padding-5">Glukoza</h4>
                                    </div>
                                    <div class="timeline_content">
                                        <b>Glukoza </b>është burimi kryesor i energjisë së trupit. Një hormon i quajtur insulinë ndihmon lëvizjen e glukozës nga qarkullimi i gjakut në qelizat. Glukoza e tepërt ose shumë e ulët në gjak mund të jetë një shenjë e një gjendjeje të rëndë mjekësore.
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="timeline_element partition-primary">
                                    <div class="timeline_title">
                                        <i class="fa fa-check-circle-o fa-2x pull-left fa-border"></i>
                                        <h4 class="text-white no-margin padding-5">Gjatësia</h4>
                                    </div>
                                    <div class="timeline_content">
                                        <p>
                                            <b>Gjatësia </b> është një faktor i rëndësishëm në caktimin e IBM (pjestohet pesha me gjatësinë në katror e një individi). Sa më e madhe IBM, predispozitat për një person që të kete diabet janë më të mëdha. Pra duhet të ushqehemi shëndetshëm!
                                        </p>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="timeline_element partition-warning">
                                    <div class="timeline_title">
                                        <i class="fa fa-hospital-o fa-2x pull-left fa-border"></i>
                                        <h4 class="light-text no-margin padding-5">Pesha</h4>
                                    </div>
                                    <div class="timeline_content">
                                        <div class="row">
                                            <div class="col-md-3 col-xs-4">
                                                <img src="~/Content/cms/assets/images/download.png" alt="imazhi" class="img-responsive" />
                                            </div>
                                            <div class="col-md-9 col-xs-8">
                                                <b>Reduktimi </b>  i kontrolluar i ushqimit ditor (reth 500kalori me pak ne dite), mundesisht i kombinuar me aktivitet fizik, mund te perbeje nje mase parandaluese per shfaqjen e diabetit tip 2 ne persona mbipeshe te predispozuar ose qe jane ne fazat fillestare te paradiabetit.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade bootstrap" id="registerModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Rekomandimet në bazë të inputeve</h4>
            </div>
            <div class="modal-body" id="content">
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-md-12">
                        <button type="button" class="btn btn-danger btn-o pull-right btn-sm" data-dismiss="modal">
                            <i class="fa fa-close"></i>
                        </button>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{

<script>
    var token = $('input[name="__RequestVerificationToken"]').val();
    var regjistro = function (btn) {
        var obj = {
            __RequestVerificationToken: token, Gjatesia: $("#Gjatesia").val(), Pesha: $("#Pesha").val(), Glukoza: $("#Glukoza").val(),
        };

        $.ajax({
            url: "/DataEntry/Create",
            cache: false,
            type: "POST",
            dataType: "json",
            data: obj,
            success: function (rs) {
                $("#content").load('@Url.Action("Rekomandimet", "DataEntry")');
                $("#Pesha").val("");
                $("#Glukoza").val("");
                $("#Gjatesia").val("");
            },
            error: function (jqXHR, error, errorThrown) {
                if (jqXHR.status && jqXHR.status == 400) {
                    console.log(jqXHR.responseText);
                } else {
                    console.log("Something went wrong");
                }
            }
        });
    };


</script>
}




<script>
    function isNumberKey(evt) {
        var charCode = (evt.which) ? evt.which : evt.keyCode
        if (charCode > 31 && (charCode < 48 || charCode > 57))
            return false;
        return true;
    }
</script>

Recommender system/Views/DataEntry/Rekomandimet.cshtml
@model IEnumerable<Recommender_system.Models.USER_RATING>
@{
    Layout = null;
}

        <div class="how-section1">
            @foreach (var item in Model)
            {
                <div class="row">
                    <div class="col-md-6 how-img">
                        <img src="@item.MEAL.ImgPath" class="rounded-circle img-fluid img-circle" alt="" />
                    </div>
                    <div class="col-md-6">
                        <h4>@item.MEAL.FoodName</h4>
                        @*<h4 class="subheading">GetLance is a great place to find more clients, and to run and grow your own freelance business.</h4>*@
                        <p class="text-muted">
                            @item.MEAL.FoodDescription
                        </p>
                    </div>
                </div>
            }
        </div>

        <style>
            .how-section1 {
                margin-top: -15%;
                padding: 10%;
            }

                .how-section1 h4 {
                    color: #ffa500;
                    font-weight: bold;
                    font-size: 30px;
                }

                .how-section1 .subheading {
                    color: #3931af;
                    font-size: 20px;
                }

                .how-section1 .row {
                    margin-top: 10%;
                }

            .how-img {
                text-align: center;
            }

                .how-img img {
                    width: 40%;
                }

            
            /* Important part */
            .modal-dialog {
                overflow-y: initial !important
            }

            .modal-body {
                height: 400px;
                overflow-y: auto;
            }
      
</style>